package hu.Sziku.RoboDog.Model;

public enum Breed {
    AFRICANHAIRLESSDOG, ALAUNT, ALPINEMASTIFF, ARGENTINEPOLARDOG, BELGIANMASTIFF, BLACKANDTANTERRIER, BLUEPAULTERRIER,
    BRAQUEDUPUY, BUCKHOUND, BULLANDTERRIER, BULLENBEISSER, CHIENGRIS, CHIRIBAYADOG, CORDOBAFIGHTINGDOG,
    CUMBERLANDSHEEPDOG, CUR, DALBODOG, DOGOCUBANO, DUMFRIESSHIREBLACKANDTANFOXHOUND, ENGLISHWATERSPANIEL,
    ENGLISHWHITETERRIER, FILADATERCEIRA, FUEGIANDOG, GRANDFAUVEDEBRETAGNE, HALLSHEELER, HAREINDIANDOG, HAWAIIANPOIDOG,
    KINGSWHITEHOUND, KURI, LAPPONIANSHEPHERD, LIMER, MARQUESANDOG, MOLOSSUS, MOSCOWWATERDOG, NORFOLKSPANIEL,
    NORMANHOUND, NORTHCOUNTRYBEAGLE, OLDCROATIANSIGHTHOUND, OLDENGLISHBULLDOG, OLDSPANISHPOINTER, OLDWELSHGREYSHEEPDOG,
    PAISLEYTERRIER, POLYNESIANDOG, RACHE, RASTREADORBRASILEIRO, SAINTJOHNSWATERDOG, SAKHALINHUSKY, SALISHWOOLDOG,
    SLEUTHHOUND, SOUTHERNHOUND, STAGHOUND, TAHITIANDOG, TAHLTANBEARDOG, TALBOTHOUND, TECHICHI, TESEM, TOYBULLDOG,
    TOYTRAWLERSPANIEL, TURNSPITDOG, TWEEDWATERSPANIEL, WELSHHILLMAN

}
